
name: release and push to central
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: shashankramesh1992
          server-password: 9845582278@mM
          gpg-private-key: E732559D8E64C9630ADD40CC7B679CB31D7CE2F5
          gpg-passphrase: admin
#       - name: build artifact
#         run: mvn clean package
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/target/*.jar"
#         token: zWjT6xL7bHIOaPtcUS9drL8KVIodUu0CSJHS
      - name: Publish to the Maven Central Repository
        run: |
          mvn verify gpg:sign install:install deploy:deploy
 #       env:
 #         MAVEN_USERNAME: shashankramesh1992
 #         MAVEN_PASSWORD: 9845582278@mM
 #         MAVEN_GPG_PASSPHRASE: admin

